logging:
  level:
    root: info
    com.law: debug
    # 下面的三行打印sql中的参数
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        min-spare-threads: 30
#    context-path: /bb/admin
    port: 8881
    

      
spring:
    jpa:
      show-sql: true
      generate-ddl: false
      properties:
        hibernate:
          format_sql: true      
      hibernate:
        ddl-auto: none
      
    thymeleaf:
        prefix: classpath:/views/
        mode : LEGACYHTML5
        cache: false
#     环境 dev|prod
    profiles:
        active: prod
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        druid:
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true
#            url: jdbc:mysql://111.231.12.224:3306/legal?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#            username: root
#            password: Falv2018
            url: jdbc:mysql://58.2.219.225:3306/a710009498?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
            username: a710009498
            password: a710009498
#     jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
#    http:
#        multipart:
#            max-file-size: 100MB
#            max-request-size: 100MB
#            enabled: true
#     指定静态资源的路径
    resources:
        static-locations: classpath:/static/,classpath:/views/
#    redis:
#        open: false  # 是否开启redis缓存  true开启   false关闭
#        database: 0
#        host: localhost
#        port: 6379
#        password:       # 密码（默认为空）
#        timeout: 6000  # 连接超时时长（毫秒）
#        pool:
#            max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
#            max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#            max-idle: 10      # 连接池中的最大空闲连接
#            min-idle: 5       # 连接池中的最小空闲连接
#druid:
# exclusions=*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*
# allow=127.0.0.1